### ISSUE TITLE
FR: Adding metadata to starter items.

### ISSUE THREAD

**Issue by Deightine** [ValkyrieofNight/StarterKits#1]
Hi Valkyrie. This is a great implementation of the starter kit idea! It was love at first sight.

Feature: Right now when an item is specified in a kit file, it doesn't seem to be adding metadata (ex. immersiveengineering:tool@1 doesn't actually give the '1' to the item.) Most of the time this is fine, but when you want a kit to include material from another mod that uses a lot of metadata (IE, techguns, tinkers, etc), it may not always be possible. Adding this should bring it into parity with how some of the loot systems work.

Also -- I found StarterKits here on Github, but noticed it doesn't populate to the Twitch lists via Curseforge for some reason. Not sure why as the two are usually seamless. I got your Lib easily enough through Twitch's search, but StarterKits wouldn't show up. I had to add it manually.

**Comment by ValkyrieofNight** [comment]
Oh will get a fix out for that soon. Thanks for letting me know!

**Comment by ValkyrieofNight** [comment]
Oh for meta try using immersiveengineering:tool:1
I use colons instead of @ symbols.

**Comment by Deightine** [comment]
Ahh. Might be useful to have a meta item in the example kit, then. Although if it would be an easy change, I'd recommend having it recognize both : and @ in that string for user compatability (for lack of better term). A lot of mods use @ to define metas in loot tables, world gen, etc, and a few that extract world data (like Lost Cities) for use by modders output it with a @. It's just a 'path of least resistance' kind of thing.

Thanks for the prompt response. :)

**Comment by ValkyrieofNight** [comment]
Thanks for the suggestion will add.

**Comment by ValkyrieofNight** [comment]
All added and release. Its just in the approval process on curseforge. Its out of alpha and in beta now which should fix the issue with it not showing in twitch :D

**Comment by Deightine** [comment]
That is wonderful news! Thank you so much. A few people I've referred it to have been really excited to see where it goes too, so you just made a bunch of peoples' day.
